version: 2

updates:
  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: weekly
      day: saturday
      time: '08:00'
      timezone: America/Sao_Paulo
    labels:
      - "area: dependencies"
      - "lang: go"

  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
      day: saturday
      time: '08:00'
      timezone: America/Sao_Paulo
    labels:
      - "area: dependencies"
      - "lang: javascript"
