# NOTE(@andreynering): The linters listed here are additions on top of
# those enabled by default:
#
# https://golangci-lint.run/usage/linters/#enabled-by-default

linters:
  enable:
    - goimports

linters-settings:
  goimports:
    local-prefixes: github.com/go-task/task
