# NOTE(@andreynering): The linters listed here are additions on top of
# those enabled by default:
#
# https://golangci-lint.run/usage/linters/#enabled-by-default

linters:
  enable:
    - goimports
    - gofmt
    - gofumpt

linters-settings:
  goimports:
    local-prefixes: github.com/go-task/task
  gofmt:
    rewrite-rules:
      - pattern: 'interface{}'
        replacement: 'any'
