# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
version: 2
pro: true

release:
  name_template: 'v{{.Version}}'

nightly:
  publish_release: true
  keep_single_release: true
  version_template: "{{incminor .Version}}-nightly"


cloudsmiths:
  - organization: "task"
    repository: "task"
    formats:
      - deb
      - rpm
      - apk
    distributions:
      deb:
        - "ubuntu/any-version"
        - "debian/any-version"
      rpm:
        - "el/any-version"
        - "fedora/any-version"
      alpine:
        - "alpine/any-version"
    component: unstable
    republish: true
    ids:
      - "!*arm64*"


includes:
  - from_file:
      path: ./.goreleaser.yml
