# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
version: 2
pro: true

release:
  name_template: 'v{{.Version}}'

builds:
  - binary: task
    ldflags:
      - -s -w -X 'github.com/go-task/task/v3/internal/version.version=vX.X.X'={{.Version}}'

nightly:
  publish_release: true
  keep_single_release: true
  version_template: "{{incminor .Version}}-nightly"

includes:
  - from_file:
      path: ./.goreleaser.yml
