# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
version: 2
pro: true

before:
  hooks:
    - cmd: 'pwd'
      output: true
    - cmd: 'ls'
      output: true
    - cmd: 'ls internal/version'
      output: true
    - cmd: 'cat internal/version/version.txt'
      output: true
    - cmd: 'echo "v{{.Version}}" > internal/version/version.txt'
    - cmd: 'cat internal/version/version.txt'
      output: true

release:
  name_template: 'v{{.Version}}'

nightly:
  publish_release: true
  keep_single_release: true
  version_template: "{{incminor .Version}}-nightly"

includes:
  - from_file:
      path: ./.goreleaser.yml
