build:
  binary: task
  main: cmd/task/task.go
  ldflags:
    - >
      -s -w 
      -X main.version={{.Version}} 
      -X main.repo=tonobo/task 
      -X main.commit={{.ShortCommit}} 
      -X main.date={{.Date}} 
  goos:
    - windows
    - darwin
    - linux
  goarch:
    - 386
    - amd64
  ignore:
    - goos: darwin
      goarch: 386
  env:
    - CGO_ENABLED=0

archives:
  - name_template: "{{.Binary}}_{{.Os}}_{{.Arch}}"

release:
  draft: true

snapshot:
  name_template: "{{.Tag}}"

checksum:
  name_template: "task_checksums.txt"
