build:
  binary: task
  main: ./cmd/task
  goos:
    - windows
    - darwin
    - linux
  goarch:
    - 386
    - amd64
    - arm
    - arm64
  goarm:
    - 6
  ignore:
    - goos: darwin
      goarch: 386
  env:
    - CGO_ENABLED=0
  ldflags:
    - -s -w # Don't set main.version.

gomod:
  proxy: true

archives:
  - name_template: "{{.Binary}}_{{.Os}}_{{.Arch}}"
    files:
      - README.md
      - LICENSE
      - completion/**/*
    format_overrides:
      - goos: windows
        format: zip

release:
  draft: true

snapshot:
  name_template: "{{.Tag}}"

checksum:
  name_template: "task_checksums.txt"

nfpms:
  - vendor: Task
    homepage: https://github.com/go-task/task
    maintainer: Andrey Nering <andrey.nering@gmail.com>
    description: Simple task runner written in Go
    license: MIT
    conflicts:
      - taskwarrior
    formats:
      - deb
      - rpm
    file_name_template: "{{.ProjectName}}_{{.Os}}_{{.Arch}}"
    contents:
      - src: completion/bash/task.bash
        dst: /etc/bash_completion.d/task
      - src: completion/fish/task.fish
        dst: /usr/share/fish/completions/task.fish
      - src: completion/zsh/_task
        dst: /usr/local/share/zsh/site-functions/_task

brews:
  - name: go-task
    description: Task runner / simpler Make alternative written in Go
    license: MIT
    homepage: https://taskfile.dev
    folder: Formula
    tap:
      owner: go-task
      name: homebrew-tap
    test:
      system "#{bin}/task", "--help"
    install: |-
      bin.install "task"
      bash_completion.install "completion/bash/task.bash" => "task"
      zsh_completion.install "completion/zsh/_task" => "_task"
      fish_completion.install "completion/fish/task.fish"
