language: go

go:
  - 1.14.x
  - 1.13.x

addons:
  apt:
    packages:
      - rpm

env:
  - GO111MODULE=on

script:
  - curl -s https://taskfile.org/install.sh | sh
  - task ci
  - git reset --hard

deploy:
  - provider: script
    skip_cleanup: true
    script: curl -sL http://git.io/goreleaser | bash
    on:
      tags: true
      condition: $TRAVIS_OS_NAME = linux
