language: go

go:
  - 1.10.x
  - 1.11.x

addons:
  apt:
    packages:
      - rpm

script:
  - go install github.com/go-task/task/cmd/task
  - task ci

deploy:
  - provider: script
    skip_cleanup: true
    script: curl -sL http://git.io/goreleaser | bash
    on:
      tags: true
      condition: $TRAVIS_OS_NAME = linux
