plugins = []
headers = []

[functions]

[functions."*"]

[build]
publish = "/home/valentin/dev/go-task/task/website/.vitepress/dist"
publishOrigin = "config"
commandOrigin = "config"
base = "/home/valentin/dev/go-task/task/website"
command = "pnpm run build"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]

[[redirects]]
from = "/changelog"
to = "/docs/changelog"
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/community"
to = "/docs/community"
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/contributing"
to = "/docs/contributing"
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/faq"
to = "/docs/faq"
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/getting-started"
to = "/docs/getting-started"
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/installation"
to = "/docs/installation"
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/integrations"
to = "/docs/integrations"
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/releasing"
to = "/docs/releasing"
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/styleguide"
to = "/docs/styleguide"
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/taskfile-versions"
to = "/docs/taskfile-versions"
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/usage"
to = "/docs/guide"
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/deprecations/*"
to = "/docs/deprecations/:splat"
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/experiments/*"
to = "/docs/experiments:splat"
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/reference/*"
to = "/docs/reference/:splat"
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/docs"
to = "/docs/guide"
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]