project_id: "574591"
api_token_env: CROWDIN_PERSONAL_TOKEN
preserve_hierarchy: true

files:
  - source: /docs/**/*
    translation: /i18n/%locale%/docusaurus-plugin-content-docs/current/**/%original_file_name%
    ignore:
      - /**/*.json

  - source: /blog/**/*
    translation: /i18n/%locale%/docusaurus-plugin-content-blog/**/%original_file_name%

  - source: /i18n/en/**/*.json
    translation: /i18n/%locale%/**/%original_file_name%
