import { SidebarsConfig } from '@docusaurus/plugin-content-docs';

export default {
  taskSidebar: [
    {
      type: 'autogenerated',
      dirName: '.'
    },
    {
      type: 'html',
      value: '<div id="sidebar-ads"></div>'
    }
  ],
} satisfies SidebarsConfig;
