name: Lint

on:
  pull_request:
  push:
    tags:
      - v*
    branches:
      - main

permissions:
  contents: read

jobs:
  lint:
    name: Lint
    strategy:
      matrix:
        go-version: [1.25.10, 1.26.x]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # v6.5.0
        with:
          go-version: ${{matrix.go-version}}

      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: golangci-lint
        uses: golangci/golangci-lint-action@ba0d7d2ec06a0ea1cb5fa41b2e4a3ab91d21278a # v9.3.0
        with:
          version: v2.12.2

  lint-jsonschema:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@ece7cb06caefa5fff74198d8649806c4678c61a1 # v6.3.0
        with:
          python-version: 3.14

      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: install check-jsonschema
        run: python -m pip install 'check-jsonschema==0.27.3'

      - name: check-jsonschema (metaschema)
        run: check-jsonschema --check-metaschema website/src/public/schema.json
