name: Website Test

on:
  pull_request:
    branches:
      - main

jobs:
  website-test:
    name: Website Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: yarn
          cache-dependency-path: ./docs/yarn.lock

      - name: Install dependencies
        run: yarn install --frozen-lockfile
        working-directory: ./docs

      - name: Test build website
        run: yarn build
        working-directory: ./docs
